version: '3'

services:
  skillsdemo:
    depends_on:
      database:
        condition: service_healthy
        restart: true
    build: .
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_DOMAIN=database
      - POSTGRES_PORT=5432
    env_file:
      - .env

  database:
    image: "postgres:15"
    ports:
      - 5444:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
