version: '3'

services:
  skillsdemo:
    depends_on:
      - database
    build: .
    ports:
      - "8081:8080"
    end_file:
      - .env
  database:
    image: "postgres:15"
    ports:
      - 5444:5432
    env_file:
      - .env