// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"skillsdemo/ent/appointment"
	"skillsdemo/ent/diagnosis"
	"skillsdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DiagnosisQuery is the builder for querying Diagnosis entities.
type DiagnosisQuery struct {
	config
	ctx              *QueryContext
	order            []diagnosis.OrderOption
	inters           []Interceptor
	predicates       []predicate.Diagnosis
	withAppointments *AppointmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiagnosisQuery builder.
func (dq *DiagnosisQuery) Where(ps ...predicate.Diagnosis) *DiagnosisQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DiagnosisQuery) Limit(limit int) *DiagnosisQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DiagnosisQuery) Offset(offset int) *DiagnosisQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DiagnosisQuery) Unique(unique bool) *DiagnosisQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DiagnosisQuery) Order(o ...diagnosis.OrderOption) *DiagnosisQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryAppointments chains the current query on the "appointments" edge.
func (dq *DiagnosisQuery) QueryAppointments() *AppointmentQuery {
	query := (&AppointmentClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(diagnosis.Table, diagnosis.FieldID, selector),
			sqlgraph.To(appointment.Table, appointment.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, diagnosis.AppointmentsTable, diagnosis.AppointmentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Diagnosis entity from the query.
// Returns a *NotFoundError when no Diagnosis was found.
func (dq *DiagnosisQuery) First(ctx context.Context) (*Diagnosis, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{diagnosis.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DiagnosisQuery) FirstX(ctx context.Context) *Diagnosis {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Diagnosis ID from the query.
// Returns a *NotFoundError when no Diagnosis ID was found.
func (dq *DiagnosisQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{diagnosis.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DiagnosisQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Diagnosis entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Diagnosis entity is found.
// Returns a *NotFoundError when no Diagnosis entities are found.
func (dq *DiagnosisQuery) Only(ctx context.Context) (*Diagnosis, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{diagnosis.Label}
	default:
		return nil, &NotSingularError{diagnosis.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DiagnosisQuery) OnlyX(ctx context.Context) *Diagnosis {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Diagnosis ID in the query.
// Returns a *NotSingularError when more than one Diagnosis ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DiagnosisQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{diagnosis.Label}
	default:
		err = &NotSingularError{diagnosis.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DiagnosisQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Diagnoses.
func (dq *DiagnosisQuery) All(ctx context.Context) ([]*Diagnosis, error) {
	ctx = setContextOp(ctx, dq.ctx, "All")
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Diagnosis, *DiagnosisQuery]()
	return withInterceptors[[]*Diagnosis](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DiagnosisQuery) AllX(ctx context.Context) []*Diagnosis {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Diagnosis IDs.
func (dq *DiagnosisQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, "IDs")
	if err = dq.Select(diagnosis.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DiagnosisQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DiagnosisQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, "Count")
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DiagnosisQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DiagnosisQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DiagnosisQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, "Exist")
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DiagnosisQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiagnosisQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DiagnosisQuery) Clone() *DiagnosisQuery {
	if dq == nil {
		return nil
	}
	return &DiagnosisQuery{
		config:           dq.config,
		ctx:              dq.ctx.Clone(),
		order:            append([]diagnosis.OrderOption{}, dq.order...),
		inters:           append([]Interceptor{}, dq.inters...),
		predicates:       append([]predicate.Diagnosis{}, dq.predicates...),
		withAppointments: dq.withAppointments.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithAppointments tells the query-builder to eager-load the nodes that are connected to
// the "appointments" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DiagnosisQuery) WithAppointments(opts ...func(*AppointmentQuery)) *DiagnosisQuery {
	query := (&AppointmentClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withAppointments = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Diagnosis.Query().
//		GroupBy(diagnosis.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DiagnosisQuery) GroupBy(field string, fields ...string) *DiagnosisGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DiagnosisGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = diagnosis.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.Diagnosis.Query().
//		Select(diagnosis.FieldStatus).
//		Scan(ctx, &v)
func (dq *DiagnosisQuery) Select(fields ...string) *DiagnosisSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DiagnosisSelect{DiagnosisQuery: dq}
	sbuild.label = diagnosis.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DiagnosisSelect configured with the given aggregations.
func (dq *DiagnosisQuery) Aggregate(fns ...AggregateFunc) *DiagnosisSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DiagnosisQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !diagnosis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DiagnosisQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Diagnosis, error) {
	var (
		nodes       = []*Diagnosis{}
		_spec       = dq.querySpec()
		loadedTypes = [1]bool{
			dq.withAppointments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Diagnosis).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Diagnosis{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withAppointments; query != nil {
		if err := dq.loadAppointments(ctx, query, nodes,
			func(n *Diagnosis) { n.Edges.Appointments = []*Appointment{} },
			func(n *Diagnosis, e *Appointment) { n.Edges.Appointments = append(n.Edges.Appointments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DiagnosisQuery) loadAppointments(ctx context.Context, query *AppointmentQuery, nodes []*Diagnosis, init func(*Diagnosis), assign func(*Diagnosis, *Appointment)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Diagnosis)
	nids := make(map[uuid.UUID]map[*Diagnosis]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(diagnosis.AppointmentsTable)
		s.Join(joinT).On(s.C(appointment.FieldID), joinT.C(diagnosis.AppointmentsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(diagnosis.AppointmentsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(diagnosis.AppointmentsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Diagnosis]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Appointment](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "appointments" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (dq *DiagnosisQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DiagnosisQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(diagnosis.Table, diagnosis.Columns, sqlgraph.NewFieldSpec(diagnosis.FieldID, field.TypeUUID))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diagnosis.FieldID)
		for i := range fields {
			if fields[i] != diagnosis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DiagnosisQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(diagnosis.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = diagnosis.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DiagnosisGroupBy is the group-by builder for Diagnosis entities.
type DiagnosisGroupBy struct {
	selector
	build *DiagnosisQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DiagnosisGroupBy) Aggregate(fns ...AggregateFunc) *DiagnosisGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DiagnosisGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, "GroupBy")
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiagnosisQuery, *DiagnosisGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DiagnosisGroupBy) sqlScan(ctx context.Context, root *DiagnosisQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DiagnosisSelect is the builder for selecting fields of Diagnosis entities.
type DiagnosisSelect struct {
	*DiagnosisQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DiagnosisSelect) Aggregate(fns ...AggregateFunc) *DiagnosisSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DiagnosisSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, "Select")
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiagnosisQuery, *DiagnosisSelect](ctx, ds.DiagnosisQuery, ds, ds.inters, v)
}

func (ds *DiagnosisSelect) sqlScan(ctx context.Context, root *DiagnosisQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
