// Code generated by ent, DO NOT EDIT.

package ent

import (
	"skillsdemo/ent/appointment"
	"skillsdemo/ent/diagnosis"
	"skillsdemo/ent/feedback"
	"skillsdemo/ent/patient"
	"skillsdemo/ent/prompt"
	"skillsdemo/ent/promptresponse"
	"skillsdemo/ent/provider"
	"skillsdemo/ent/schema"
	"skillsdemo/ent/survey"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appointmentFields := schema.Appointment{}.Fields()
	_ = appointmentFields
	// appointmentDescID is the schema descriptor for id field.
	appointmentDescID := appointmentFields[0].Descriptor()
	// appointment.DefaultID holds the default value on creation for the id field.
	appointment.DefaultID = appointmentDescID.Default.(func() uuid.UUID)
	diagnosisFields := schema.Diagnosis{}.Fields()
	_ = diagnosisFields
	// diagnosisDescLastUpdated is the schema descriptor for lastUpdated field.
	diagnosisDescLastUpdated := diagnosisFields[2].Descriptor()
	// diagnosis.DefaultLastUpdated holds the default value on creation for the lastUpdated field.
	diagnosis.DefaultLastUpdated = diagnosisDescLastUpdated.Default.(time.Time)
	// diagnosisDescID is the schema descriptor for id field.
	diagnosisDescID := diagnosisFields[0].Descriptor()
	// diagnosis.DefaultID holds the default value on creation for the id field.
	diagnosis.DefaultID = diagnosisDescID.Default.(func() uuid.UUID)
	feedbackFields := schema.Feedback{}.Fields()
	_ = feedbackFields
	// feedbackDescID is the schema descriptor for id field.
	feedbackDescID := feedbackFields[0].Descriptor()
	// feedback.DefaultID holds the default value on creation for the id field.
	feedback.DefaultID = feedbackDescID.Default.(func() uuid.UUID)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescID is the schema descriptor for id field.
	patientDescID := patientFields[0].Descriptor()
	// patient.DefaultID holds the default value on creation for the id field.
	patient.DefaultID = patientDescID.Default.(func() uuid.UUID)
	promptFields := schema.Prompt{}.Fields()
	_ = promptFields
	// promptDescSortOrder is the schema descriptor for sort_order field.
	promptDescSortOrder := promptFields[1].Descriptor()
	// prompt.SortOrderValidator is a validator for the "sort_order" field. It is called by the builders before save.
	prompt.SortOrderValidator = promptDescSortOrder.Validators[0].(func(int) error)
	// promptDescAdditionalFeedback is the schema descriptor for additional_feedback field.
	promptDescAdditionalFeedback := promptFields[5].Descriptor()
	// prompt.DefaultAdditionalFeedback holds the default value on creation for the additional_feedback field.
	prompt.DefaultAdditionalFeedback = promptDescAdditionalFeedback.Default.(bool)
	// promptDescID is the schema descriptor for id field.
	promptDescID := promptFields[0].Descriptor()
	// prompt.DefaultID holds the default value on creation for the id field.
	prompt.DefaultID = promptDescID.Default.(func() uuid.UUID)
	promptresponseFields := schema.PromptResponse{}.Fields()
	_ = promptresponseFields
	// promptresponseDescPromptIndex is the schema descriptor for prompt_index field.
	promptresponseDescPromptIndex := promptresponseFields[1].Descriptor()
	// promptresponse.PromptIndexValidator is a validator for the "prompt_index" field. It is called by the builders before save.
	promptresponse.PromptIndexValidator = promptresponseDescPromptIndex.Validators[0].(func(int) error)
	// promptresponseDescID is the schema descriptor for id field.
	promptresponseDescID := promptresponseFields[0].Descriptor()
	// promptresponse.DefaultID holds the default value on creation for the id field.
	promptresponse.DefaultID = promptresponseDescID.Default.(func() uuid.UUID)
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescID is the schema descriptor for id field.
	providerDescID := providerFields[0].Descriptor()
	// provider.DefaultID holds the default value on creation for the id field.
	provider.DefaultID = providerDescID.Default.(func() uuid.UUID)
	surveyFields := schema.Survey{}.Fields()
	_ = surveyFields
	// surveyDescID is the schema descriptor for id field.
	surveyDescID := surveyFields[0].Descriptor()
	// survey.DefaultID holds the default value on creation for the id field.
	survey.DefaultID = surveyDescID.Default.(func() uuid.UUID)
}
