// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Appointment is the predicate function for appointment builders.
type Appointment func(*sql.Selector)

// Diagnosis is the predicate function for diagnosis builders.
type Diagnosis func(*sql.Selector)

// Feedback is the predicate function for feedback builders.
type Feedback func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Prompt is the predicate function for prompt builders.
type Prompt func(*sql.Selector)

// PromptResponse is the predicate function for promptresponse builders.
type PromptResponse func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Survey is the predicate function for survey builders.
type Survey func(*sql.Selector)
